spring.data.mongodb.port: 27021
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex"
  level:
    com.github.rahulsom: DEBUG
    grooves.boot: DEBUG
    root: ERROR
